### ISSUE TITLE
Support for localtunnel.me

### ISSUE THREAD

**Issue by jabrena** [yudai/gotty#103]
I am testing gotty with ngrok and I didn't find any problem but with localtunnel, http://localtunnel.me/ I can receive the data from my host. 
What is the problem?
using DevTools in Chrome I don't receive any problem.

Many thanks in advance

Juan Antonio

**Comment by yudai** [comment]
I gave localtunnel.me a try and succeeded to open Gotty on Chrome. Probably you have something wrong in your network.

**Comment by yudai** [comment]
Closing as no recent activities. Please feel free to reopen if needed.
