### ISSUE TITLE
gotty doesn't close connections unless a write times out

### ISSUE THREAD

**Issue by colemickens** [yudai/gotty#109]
https://gist.github.com/anonymous/fef3a88f2d2277dc94ca97046e0392e4

You can see the first client connects, but then disconnects (I closed the browser window) after 8 seconds. Nothing is being sent to TTY at all. This is printed:

```
2016/07/29 17:02:13 websocket: close 1001 
```

But we never see the actual client connection get closed.

The second client connects. But I start `top` inside so that something is writing to stdout. Then I close the browser window. This is printed:

```
2016/07/29 17:02:22 websocket: close 1001 
2016/07/29 17:02:23 websocket: close sent
2016/07/29 17:02:24 Connection closed: 66.235.2.123:60752
```

It seems like the client connection isn't being cleaned up in cases where there is no write going on to make gotty notice the disconnect and send SIGHUP.

(In this case, it means if a user opens a `gotty` session and then closes it immediately, resources get left around that won't be cleaned up until `gotty` itself is killed.

**Comment by yudai** [comment]
Should be fixed in the master branch. Let me know when it still exists.
