### ISSUE TITLE
Proxy thought with Gotty

### ISSUE THREAD

**Issue by nephaste** [yudai/gotty#116]
Hi Yudai,

not sure it is a Gotty problem or on Qnap

we have an HTTP proxy based on Apache 2.2.x, allowing to use the standard 8080 port from QTS

when i try to use the proxy.. gotty is launching but i have a white page on browser.
Works perfectly when proxy is disable on QPKG configuration

it will be perfect if i can use it with a web proxy...

thanks for your feedback

**Comment by yudai** [comment]
Try this one:

```
ProxyPass /your_path/ws      ws://gotty.example.com:8080/ws
ProxyPass /your_path/      http://gotty.example.com:8080/
ProxyPassReverse /your_path/ws ws://gotty.example.com:8080/ws
ProxyPassReverse /your_path/ http://gotty.example.com:8080/
```

**Comment by nephaste** [comment]
I am checking with Qnap R&D, look like the proxypass feature from last SDK miss this instruction

i am not sure how implement this ...

Gotty is actually running on port :8586 on Qnap, hope i could make run on :8080/gotty

I ll keep you update

**Comment by yudai** [comment]
Closing as no recent activities. Feel free to reopen this issue if you still have the issue.
