### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by likezjuisee** [yudai/gotty#120]
when I run the command "./gotty -w top", some exception happened, as below:

goroutine 11 [running]:
net/http.func路011()
        /usr/lib/golang/src/net/http/server.go:1130 +0xbb
github.com/elazarl/go-bindata-assetfs.(_AssetFS).Open(0xc20803d1d0, 0xc2080786e0, 0x11, 0x0, 0x0, 0x0, 0x0)
        /home/like/goworkspace/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:149 +0x232
net/http.serveFile(0x7f4dd5439680, 0xc208078500, 0xc208034d00, 0x7f4dd54382a8, 0xc20803d1d0, 0x7ab470, 0x1, 0x7ab401)
        /usr/lib/golang/src/net/http/fs.go:389 +0x478
net/http.(_fileHandler).ServeHTTP(0xc208082750, 0x7f4dd5439680, 0xc208078500, 0xc208034d00)
        /usr/lib/golang/src/net/http/fs.go:452 +0x1b1
net/http.func路012(0x7f4dd5439680, 0xc208078500, 0xc208034d00)
        /usr/lib/golang/src/net/http/server.go:1297 +0xe1
net/http.HandlerFunc.ServeHTTP(0xc20802eba0, 0x7f4dd5439680, 0xc208078500, 0xc208034d00)
        /usr/lib/golang/src/net/http/server.go:1265 +0x41
net/http.(_ServeMux).ServeHTTP(0xc20803d230, 0x7f4dd5439680, 0xc208078500, 0xc208034d00)
        /usr/lib/golang/src/net/http/server.go:1541 +0x17d
github.com/yudai/gotty/app.func路002(0x7f4dd5439680, 0xc208078500, 0xc208034d00)
        /home/like/goworkspace/src/github.com/yudai/gotty/app/app.go:408 +0xe3
net/http.HandlerFunc.ServeHTTP(0xc2080827e0, 0x7f4dd5439680, 0xc208078500, 0xc208034d00)
        /usr/lib/golang/src/net/http/server.go:1265 +0x41
net/http.(_ServeMux).ServeHTTP(0xc20803d290, 0x7f4dd5439680, 0xc208078500, 0xc208034d00)
        /usr/lib/golang/src/net/http/server.go:1541 +0x17d
github.com/yudai/gotty/app.func路001(0x7f4dd5439648, 0xc2080445a0, 0xc208034d00)
        /home/like/goworkspace/src/github.com/yudai/gotty/app/app.go:400 +0xe2
net/http.HandlerFunc.ServeHTTP(0xc208082800, 0x7f4dd5439648, 0xc2080445a0, 0xc208034d00)
        /usr/lib/golang/src/net/http/server.go:1265 +0x41
github.com/braintree/manners.(_gracefulHandler).ServeHTTP(0xc2080780a0, 0x7f4dd5439648, 0xc2080445a0, 0xc208034d00)
        /home/like/goworkspace/src/github.com/braintree/manners/server.go:277 +0x81
net/http.serverHandler.ServeHTTP(0xc208042060, 0x7f4dd5439648, 0xc2080445a0, 0xc208034d00)
        /usr/lib/golang/src/net/http/server.go:1703 +0x19a
net/http.(_conn).serve(0xc208044500)
        /usr/lib/golang/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/lib/golang/src/net/http/server.go:1751 +0x35e
2016/09/19 10:09:19 http: panic serving 10.18.131.59:61116: runtime error: invalid memory address or nil pointer dereference
goroutine 12 [running]:
net/http.func路011()
        /usr/lib/golang/src/net/http/server.go:1130 +0xbb

**Comment by LINKIWI** [comment]
For anyone else experiencing this problem, I was also getting this exception whenever a client issued a `GET /`. I "fixed" this by re-initializing my Go path:

```bash
$ rm -rf $GOPATH
$ go get github.com/yudai/gotty
```

Not really a proper solution but hopefully this helps someone

**Comment by yudai** [comment]
How did you get the binary which raise the error?

**Comment by yudai** [comment]
Closing as no recent activities. Please feel free to reopen if needed.
