### ISSUE TITLE
Failed to install gotty on Ubuntu

### ISSUE THREAD

**Issue by rtwk** [yudai/gotty#125]
How to install gotty on Ubuntu? Run "go get github.com/yudai/gotty", in a folder /home/user1/work
 it created a folder structure in "pkg' folder. But when I run a command lik - "gotty -w vim test.txt
" it says No command 'gotty' found. What is going wrong?

**Comment by sword-huang** [comment]
Do you add the GOPATH into your PATH as below?
$ export PATH=$GOPATH/bin:$PATH

**Comment by rtwk** [comment]
I did. I have two users. user1 and user2. Go is installed as user1. I did "go get .." as user1 in a dir within homedir of user1. I did  export PATH=$GOPATH/bin:$PATH as user1. But failed to run gotty (gotty not found). I actually want to run gotty user2.

**Comment by sword-huang** [comment]
After you run "go get github.com/yudai/gotty", gotty will be downloaded to $GOPATH/bin.
Maybe you can check whether gotty is exist in $GOPATH/bin or not!

**Comment by woodpenker** [comment]
I have the same problem.But I fix it like this.
I just download the release for linux ,tar it & copy the "gotty" file to the place I want to start it.(just as I do /home).then I run /home/gotty -w vim test.txt.It works!

**Comment by yudai** [comment]
Closing as it's a little bit old issue. Thanks for your feedbacks.
Please reopen if the is still outstanding.
