### ISSUE TITLE
Need a way to use gotty as a golang library with the ability to  customize the terminal backend.

### ISSUE THREAD

**Issue by jizhilong** [yudai/gotty#128]
Hi @yudai , thanks for this awesome project.I am currently looking for a solution to provide remote access to docker containers, and `gotty` inspires me a lot.

Actually I have worked out a draft based on `gotty` in this [commit](https://github.com/jizhilong/gotty/commit/1012fa7c7e74a330fbd7ef82b2f16525b4b8cc91),which works by replacing the original pty based backend with a websocket which is returned by docker-daemon's RESTful API.

The function of this draft is essentially equivalent with `gotty -w docker exec -it <container> bash`，the reason I did not use such command directly is we want more precisely control over `docker exec` we created, and one process for one remote access request may cause some performance issue.

Bu as you can see in the [commit](https://github.com/jizhilong/gotty/commit/1012fa7c7e74a330fbd7ef82b2f16525b4b8cc91), implementing such feature based on the current code base of `gotty` is quite simple and straight forward, even the original function get broken.

So, I propose to do some refactor, by splitting `gotty` into three parts:

1.  the first part is **app**, which handles the transport, authentication and secure.
2. the second part is **terminal backends**, which provide terminal ios.**app** calls **terminal backends** via interface, so that we can add more **terminal backends** easily without breaking other parts of `gotty`.
3. the last part is the cli interface, which combines **app** and a concrete **terminal backend** implementation to provide full functionality.

**Comment by yudai** [comment]
Sounds good to me. I actually wanted to refactor gotty but didn't have time to do so.
I'd like to review if you could send a PR.

**Comment by jizhilong** [comment]
GOOD! I'd love to contribute a PR for the refactoring.

**Comment by jizhilong** [comment]
Hi @yudai ,I opened a PR for the refactoring, and built a tool based on refactored gotty: [goexec](https://github.com/jizhilong/goexec)

**Comment by ffledgling** [comment]
Hi @yudai, I wanted to take this a step further so that we could build the command to "exec" programatically (provide a function that returns the command to exec), as well as add the ability to run gotty-server + client on separate URLs/machines/hosts (basically Cross-Origin web-sockets).

I actually got this working by tweaking the gotty code, but I'd like it if we could refactor the "App" object/struct to make this easier.

**Comment by yudai** [comment]
I think I can release something maybe next week.

**Comment by ffledgling** [comment]
@yudai Will this be in the 0.14 release by any chance? :)

**Comment by yudai** [comment]
will be included. but I'm making some interface changes now.

**Comment by yudai** [comment]
you can find some progress in the wip branch.

**Comment by yudai** [comment]
This change will be the main topic for the release v2.0.0, because it requires some major refactoring.

**Comment by yudai** [comment]
Merged :)
