### ISSUE TITLE
Issues - xlose connection

### ISSUE THREAD

**Issue by outkastm** [yudai/gotty#132]
When running i get the close connection right after accessing the url. Tried to access different devices
`2017/01/26 00:10:54 192.168.2.158:62858 200 GET /auth_token.js
2017/01/26 00:10:54 192.168.2.158:62857 200 GET /js/hterm.js
2017/01/26 00:10:54 192.168.2.158:62858 200 GET /favicon.png
2017/01/26 00:10:54 192.168.2.158:62860 200 GET /js/gotty.js
2017/01/26 00:10:54 New client connected: 192.168.2.158:62861
2017/01/26 00:10:54 Command is running for client 192.168.2.158:62861 with PID 5625 (args=""), connections: 1
2017/01/26 00:10:54 192.168.2.158:62861 101 GET /ws
2017/01/26 00:10:54 Command exited for: 192.168.2.158:62861
2017/01/26 00:10:54 Connection closed: 192.168.2.158:62861, connections: 0
2017/01/26 00:10:54 read tcp 192.168.2.85:3333->192.168.2.158:62861: use of closed network connection

`

**Comment by yudai** [comment]
I think connection related issues like this should be fixed in the master branch. Let me know when it still exists.
