### ISSUE TITLE
Remove duplicated code to close the WS connection

### ISSUE THREAD

**Issue by supereagle** [yudai/gotty#140]
There are many duplicated code `conn.Close()` in the method `handleWS()` of [app/app.go](https://github.com/yudai/gotty/blob/master/app/app.go#L313-L410). It is better to move this into `defer` after the connection opened.

**Comment by yudai** [comment]
Thanks for the comment. This will be fixed in the next release.

**Comment by yudai** [comment]
Now fixed in the master branch.
