### ISSUE TITLE
[Question] Using gotty as a library/using gotty server bits only

### ISSUE THREAD

**Issue by ffledgling** [yudai/gotty#141]
I was wondering if it's okay to use gotty as a library to write my own terminal-over-websocket server application.
Essentially I'd like to extend the functionality (client specifies what commands to run, cross-origin connections etc.) and was wondering if gotty is intended to be used as a library or might have frequent breaking changes in the contact between the client and the server (gotty subprotocol, auth methods etc)

Currently the code seems to be tailored to simply the gotty client, is this intention or would be open to extending the gotty project to support it's use a library for things other than the gotty client?

**Comment by yudai** [comment]
I think this duplicates #128.
Some code refactoring is in (slowly) progress to make gotty as  a library at the wip branch.

**Comment by ffledgling** [comment]
@yudai Hi, I've left a comment on that PR. Would you like to close this one and continue discussion on that one? I've proposed a scope increase, but I'd be happy to contribute to the effort.

**Comment by yudai** [comment]
@ffledgling Let's close this issue and keep discussion at #128
