### ISSUE TITLE
question: Connecting to a NATed device

### ISSUE THREAD

**Issue by joeblew99** [yudai/gotty#144]
i have my raspberrypi at home on a non static IP.
It calls out to google storage to tell it its Ip address.

So i was wondering if i can connect to it with gotty using that IP address and the websocket connection will work ?

**Comment by yudai** [comment]
If you set up a port forwarding on your router, you should be able to access your gotty process using the IP address reported to your google storage and the port you set to your router.

**Comment by joeblew99** [comment]
true, but i cant do that.
the router is locked by my landlord :)

yes thats why i plan to store the IP. Kind of like a poor many dynamic dns
service :)

**Comment by yudai** [comment]
[ngrok](https://ngrok.com/) could be what you want?

**Comment by gedw99** [comment]
good idea.. will see what i can do. thanks for your help...
