### ISSUE TITLE
Switch to xterm.js

### ISSUE THREAD

**Issue by yudai** [yudai/gotty#147]
It seems xterm.js supports IMEs to input non-ASCII characters such as CJK.
It's worth trying to evaluate it and switch to it if it works well.
This is a braking change for configurations, so will be a part of v2.0.0 release.

**Comment by databus23** [comment]
Very exited about this because the copy&paste support is also way better on xterm across browsers.

**Comment by yudai** [comment]
Slowly, but work is in progress at #151.

**Comment by yudai** [comment]
Done. You can still use hterm by giving `--term hterm`.
