### ISSUE TITLE
Error: SHA256 mismatch

### ISSUE THREAD

**Issue by jirayuzanroo** [yudai/gotty#148]
i got status 'Error: SHA256 mismatch' after i had installed with 'brew install yudai/gotty/gotty'

how should i do? 
thank you.

**Comment by jirayuzanroo** [comment]
my environment are 
Homebrew 1.2.1
go version go1.8.1 darwin/amd64
and OSX 10.12.4

**Comment by yudai** [comment]
Thank you for a report. Fixed!
