### ISSUE TITLE
Minified resources

### ISSUE THREAD

**Issue by khash** [yudai/gotty#149]
It would be great if a minified version of `hterm.js`are included in the binary.
<img width="562" alt="screen shot 2017-06-19 at 17 49 51" src="https://user-images.githubusercontent.com/1121822/27296184-c9d9b434-5517-11e7-9953-ada158e26e22.png">

**Comment by yudai** [comment]
Thank you for the suggestion. It should be done in the next major release.

**Comment by yudai** [comment]
now webpack minifies the bundled code. Thanks!
