### ISSUE TITLE
Can not use IME to input CJK

### ISSUE THREAD

**Issue by wenerme** [yudai/gotty#15]
`gotty -w vim`

**Comment by yudai** [comment]
Confirmed a problem. This looks a problem of hterm and maybe takes time to fix.

**Comment by pp00pp** [comment]
Hi

**Comment by yudai** [comment]
HI, unfortunately, this fix will be not done soon. It requires a big change to hterm.

**Comment by tylerlong** [comment]
👍

**Comment by holys** [comment]
It seems xterm.js can support CJK

see https://github.com/zeit/hyper/issues/1275

**Comment by holys** [comment]
@wenerme  I have make a [fork](https://github.com/holys/gotty) version and replace hterm.js with xterm.js. Now it support CJK and IME. Code mostly adapted from https://github.com/tsl0922/ttyd/

**Comment by yudai** [comment]
handling in #147

**Comment by yudai** [comment]
Now the default terminal is xterm.js. So you should be able to enable your IME :)
