### ISSUE TITLE
WebSocket server response missing Sec-WebSocket-Protocol header

### ISSUE THREAD

**Issue by richardcarls** [yudai/gotty#161]
### What version of GoTTY are you using (`gotty --version`)?
v1.0.0

### What operating system are you using?
Debian (Stretch)

### What did you do?
Execute /bin/login with GoTTY and open URL in Chrome v59

### What did you expect to see?
Login prompt

### What did you see instead?
White screen

If possible, please provide the output of the command and your browser's console output.

```
WebSocket connection to 'wss://example.com:8080/ws' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received
  openWs @ gotty.js:9
```

Seems like Chrome is more strict is expecting "gotty" back on the server response if requested by the client. The response is indeed missing the `Sec-WebSocket-Protocol` header:

```
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: z7ptnNT++hictERtbeJy5WrvW6I=
```

If you remove the second argument `protocols` when creating the WebSocket on the client, it fixes the issue for Chrome, but it would be better to return the protocol in server responses.

**Comment by yudai** [comment]
Thank you for the report.

It looks interesting. The server should return `gotty` as a subprotocol.
https://github.com/yudai/gotty/blob/release-1.0/app/app.go#L125

Is there any proxy between your client and server?

**Comment by richardcarls** [comment]
Sorry, yes I have it running behind [traefik](https://github.com/containous/traefik). It works as expected without the reverse proxy; a bug or mis-configuration with traefik is to blame, so I will close this issue. I'll post back if I find a solution, thanks!
