### ISSUE TITLE
Random URL generation

### ISSUE THREAD

**Issue by yudai** [yudai/gotty#17]
URL generation for something like an authentication alternative.

Add an option to generate URLs like:

```
https://host:8080/nairj3gnw5ja39r23
```

**Comment by mattn** [comment]
@shoz thanks. @yudai hmm, each time that new feature is added, function arguments are grown. seems to be ugly. How about to take a struct bundling options?

**Comment by yudai** [comment]
@mttn could you explain about "struct bundling options"?

**Comment by yudai** [comment]
Like thi https://github.com/yudai/gotty/blob/options/app/app.go#L23 ?

**Comment by mattn** [comment]
Ah, I write comment similar to your's just now. :)

**Comment by yudai** [comment]
@mttn, sorry. I suddenly realized just you had meant and wrote the code. Now it looks better than the previous one. Thanks for the suggestion.
