### ISSUE TITLE
Followed instructions with go get, not working

### ISSUE THREAD

**Issue by AugiteSoul** [yudai/gotty#171]
I use go 1.9 with raspbian.
I used showterm to record what I did: https://showterm.io/cb14bb0eed3c2c78bf497

**Comment by yudai** [comment]
Thank you for the report.
Since `make` tries to build JS files, you need `npm`. However, the repo has prebuild files already, so the task is not mandatory. I removed the task from `make` not to require installing `npm`.

**Comment by AugiteSoul** [comment]
I have npm, I retried, but it gave me the same error. What should I do?

**Comment by yudai** [comment]
I updated the Makefile again. Could you try it on the latest master?

**Comment by yudai** [comment]
Closing as no recent activities. Feel free to reopen if you still have the issue.
