### ISSUE TITLE
Open terminal in specific directory

### ISSUE THREAD

**Issue by admindaspanel** [yudai/gotty#172]
If I initialize Gotty with this parameters:

`gotty --permit-arguments /myshellscript.sh`

And the URL with which access is:

`https://mygottyserver/?dir=/mydir`

I can assume that in myshellscript.sh:

```
#!/bin/sh
cd "$1"
exec sh
```

Will it open a shell with the current directory = mydir which is the value passed in the dir argument of the URL?

And if I call several times the same URL changing the url parameter on each of the times will I have a new web console positioned in the directory informed via the URL parameter?

**Comment by yudai** [comment]
You need to use `arg` to pass parameter values. I think what you want is `https://mygottyserver/?arg=/mydir`. When you have two or more parameters, you can simply add more `arg` to your query string like `https://mygottyserver/?arg=/mydir&arg=/some/where/else`.

>And if I call several times the same URL changing the url parameter on each of the times will I have a new web console positioned in the directory informed via the URL parameter?

Yes.

Note that, it could be a security volatility if you don't sanitize or check any parameter values. In your example, anyone who know the URL can try "directory traversal" to access hidden files.
