### ISSUE TITLE
how to build a develop environment?

### ISSUE THREAD

**Issue by smileboywtu** [yudai/gotty#184]
# When file a bug report (see below for feature requests)

to build a develop environment locally

### What version of GoTTY are you using (`gotty --version`)?

latest master

### What operating system and browser are you using?

linux fedora 26

### What did you do?

If possible, please provide the command you ran.

try to improve something

### What did you expect to see?

add random url content myself

### What did you see instead?

If possible, please provide the output of the command and your browser's console output.

# When file a new feature proposal

Please provide an actual usecase that requires your new feature.

**Comment by yudai** [comment]
Hello, could you describe a bit more about your problem?

**Comment by smileboywtu** [comment]
i clone this into my go/src/github/smileboywtu/, but all import are yudai/gotty, so i can't build locally, but finally i use `go get` and download src into src/github/yudai to fix this. the problem can be closed.

**Comment by yudai** [comment]
Got it! Thank you for using/improving gotty.
