### ISSUE TITLE
Incomplete unicode support

### ISSUE THREAD

**Issue by linnik** [yudai/gotty#19]
Unicode symbols are not interpreted correctly during input from the browser, while terminal-to-browser utf output works fine.
<img width="427" alt="gotty-unicode-bug" src="https://cloud.githubusercontent.com/assets/902428/9322529/8b7e2272-4585-11e5-88da-0b804664b36f.png">
1st cmd - terminal input
3rd cmd - browser input
osx yosemite, darwin_amd64 gotty pre-release

**Comment by yudai** [comment]
How did you input unicode characters?

**Comment by linnik** [comment]
with my cyrillic keyboard

**Comment by yudai** [comment]
Thanks. I succeeded reproducing the issue.

**Comment by yudai** [comment]
I think I fixed the problem. I have no keyboard that can directly input non-ascii characters, however at least input from the clipboard (paste) is now working well.

**Comment by linnik** [comment]
works as expected now, thanks
