### ISSUE TITLE
Feature: Livereload

### ISSUE THREAD

**Issue by schickling** [yudai/gotty#2]
It would be nice if `gotty` would tell the webbrowser to automatically reload the page if an old session was finished/killed and a new one was started on the same port. Should be easy to implement on the client side.

Keep up the good work! This package is a big one for me! :+1:

**Comment by yudai** [comment]
It's hard to distinguish the different between intended process termination and unexpected process termination from the client side. Therefore, reconnecting automatically can be bothering in same cases.
I guess I need to add an option to the gotty command or add a select box in the client side. But still I'm not sure which is better.

**Comment by yudai** [comment]
Implemented  a new `--auto-reconnect` option. You can provide seconds to try reconnect.

**Comment by schickling** [comment]
Great! Good job!
