### ISSUE TITLE
Gotty behind NGINX does not seems to work , gotty gives 403 error to NGINX

### ISSUE THREAD

**Issue by rajeget** [yudai/gotty#202]
### What version of GoTTY are you using (`gotty --version`)?
1.0.1

### What operating system and browser are you using?
OSX and Firefox

### What did you do?
1.Created a gotty docker image.
2.Installed nginx on it 
3. Configured nginx for websocket proxy , tried nginx config ( https://www.nginx.com/blog/websocket-nginx/ ) and than this (https://github.com/raincoats/nginx.gotty.proxy)  
4. When connection to gotty it does not work, error is that after 4 setps gotty server gives 403. 
Flow from firefox developer tool is 
GET /  = RESULT HTTP 200
GET auth_token.js = RESULT HTTP 200
GET gotty.js = RESULT HTTP 200
GET hterm.js = RESULT HTTP 200
GET ws = RESULT HTTP 403

### What did you expect to see?
run gotty behind nginx, 

### What did you see instead?
nginx works perfetly for websocket , but for gotty its showing 403. 
![screen shot 2018-03-23 at 11 08 06 am](https://user-images.githubusercontent.com/16147424/37813202-14df8232-2e8a-11e8-8490-b7e48d763860.png)

**Comment by rajeget** [comment]
Could finally solve it . Please see https://github.com/rajeget/websocket-nginx/

**Comment by fangyue6** [comment]
it works , thanks
