### ISSUE TITLE
could not find upgrade header with token 'websocket'

### ISSUE THREAD

**Issue by hong-duc** [yudai/gotty#204]
### What version of GoTTY are you using (`gotty --version`)?
gotty_2.0.0-alpha.3_linux_amd64

### What operating system and browser are you using?
centos

### What did you do?
Start gotty
If possible, please provide the command you ran.
gotty -p 8000 pm2 log 107 

### What did you expect to see?
pm2 log

### What did you see instead?
connection close
If possible, please provide the output of the command and your browser's console output.
```
2018/04/03 14:49:49 GoTTY is starting with command: pm2 log 107
2018/04/03 14:49:49 HTTP server is listening at: http://:::8000/
2018/04/03 14:49:49 Alternative URL: http://127.0.0.1:8000/
2018/04/03 14:49:49 Alternative URL: http://::1:8000/
2018/04/03 14:49:49 Alternative URL: http://172.16.6.46:8000/
2018/04/03 14:49:49 Alternative URL: http://fe80::20c:29ff:fe5a:a277:8000/
2018/04/03 14:49:49 Alternative URL: http://172.17.0.1:8000/
2018/04/03 14:49:49 Alternative URL: http://fe80::42:cbff:fe37:405f:8000/
2018/04/03 14:49:49 Alternative URL: http://fe80::9c5e:eff:fe5f:ef:8000/
2018/04/03 14:49:49 Alternative URL: http://fe80::ac7f:88ff:fee7:c931:8000/
2018/04/03 14:49:49 Alternative URL: http://fe80::b465:9ff:fef4:791f:8000/
2018/04/03 14:49:49 Alternative URL: http://fe80::9c31:d5ff:feda:15d9:8000/
2018/04/03 14:49:52 127.0.0.1:43902 200 GET /
2018/04/03 14:49:53 127.0.0.1:43904 200 GET /css/index.css
2018/04/03 14:49:53 127.0.0.1:43906 200 GET /css/xterm_customize.css
2018/04/03 14:49:53 127.0.0.1:43908 200 GET /css/xterm.css
2018/04/03 14:49:53 127.0.0.1:43914 200 GET /auth_token.js
2018/04/03 14:49:53 127.0.0.1:43910 200 GET /config.js
2018/04/03 14:49:53 127.0.0.1:43912 200 GET /js/gotty-bundle.js
2018/04/03 14:49:53 New client connected: 127.0.0.1:43916, connections: 1/0
2018/04/03 14:49:53 Connection closed by websocket: could not find upgrade header with token 'websocket': 127.0.0.1:43916, connections: 0/0
```
Browser Console log
```
WebSocket connection to 'ws://gotty.lamgigio.net/ws' failed: Error during WebSocket handshake: Unexpected response code: 400
```

I use nginx to proxy the request, with this config
```
            proxy_http_version 1.1;
            proxy_set_header X-Real-IP  $remote_addr;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_cache_bypass $http_upgrade;
            proxy_set_header Host $host;
            proxy_pass http://127.0.0.1:8000;
```
But when I start request it throw error `could not find upgrade header with token 'websocket'`

Thank you

**Comment by thallada** [comment]
I am getting the same error while also proxying the request through nginx. @hong-duc did you solve this issue?

I want to be able to proxy through nginx so that I can have a nice pretty domain name without a port number that maps to the port on localhost that gotty is running on.

**Comment by thallada** [comment]
Nevermind, I found a solution to this. You have to enable websocket connections through the nginx proxy by [adding the Connection and Upgrade headers](https://www.nginx.com/blog/websocket-nginx/):

```
...
proxy_pass http://127.0.0.1:8000;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "Upgrade";
```

**Comment by fangyue6** [comment]
I am getting the error while also proxying the request through nginx. @thallada @hong-duc how did you config the nginx.conf ?

my Browser Console log
`gotty-bundle.js:88 WebSocket connection to 'ws://tx.itisyue.cn/gottyws' failed: Error during WebSocket handshake: Unexpected response code: 200`

my nginx.conf 

`    upstream gotty_server {
        server tx.itisyue.cn:9000;
    }
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   html;
            index  index.html index.htm;
        }
        location /gottyws {
            proxy_pass http://gotty_server;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
        location /gotty {
            proxy_pass http://gotty_server;
            # enables WS support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
        location ~ .*\.(js|css|jpg|jpeg|gif|png|ico|pdf|txt)$ {
            proxy_pass http://gotty_server;
            # enables WS support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection  "upgrade";
        }`
