### ISSUE TITLE
Release does not include files needed for building.

### ISSUE THREAD

**Issue by rkeene** [yudai/gotty#22]
Running "make" against the provided makefile immediately fails with:

    make: *** No rule to make target `libapps/hterm/js/*.js', needed by `bindata/hterm.js'.  Stop.

libapps/ is an empty directory.

**Comment by KLuka** [comment]
Maybe you didn't correctly clone the repo. Recursive more has to be used, so that submodules are downloaded too. Try this command:

```
git clone --recursive https://github.com/yudai/gotty.git
```

**Comment by shinji62** [comment]
you need to init/ update submodule

**Comment by yudai** [comment]
Added a note in README. Thank you for the comments!
