### ISSUE TITLE
Custom Fonts

### ISSUE THREAD

**Issue by cj** [yudai/gotty#23]
It would be nice to be able to use custom fonts.  I added this with the raw one, it was pretty straight forward if I remember correctly.

**Comment by ewnd9** [comment]
What about injecting any html tags into terminal in browser? Use case: make url clickable :sunglasses:

**Comment by cj** [comment]
@ewnd9 that would be cool.  I was also thinking a `.gotty` file to allow for hterm override preferences etc....

**Comment by haliphax** [comment]
+1 This would be AWESOME! I'm using GoTTY as a web bridge to my telnet BBS, but the artwork winds up looking a little janky. More closely mirroring the Linux default terminal color scheme would be nice, too -- I'll open up a separate issue for that.

**Comment by yudai** [comment]
Supporting a config file sounds good.

**Comment by yudai** [comment]
Implemented. Now you can write profile files to customize font size and color, cursor color, and so on.

**Comment by haliphax** [comment]
Sorry -- I mean which font the page is rendered in. Meaning DejaVu Sans Mono, Courier, etc.

**Comment by yudai** [comment]
Try `~/.gotty` with

```
font-family = "DejaVu Sans Mono"
```

**Comment by haliphax** [comment]
Awesome. Thanks!

**Comment by yudai** [comment]
@haliphax I accessed your endpoint and confirmed that your BBS showed texts with "DejaVu Sans Mono". I guess you forgot to install the font in your client machine?

Before installing the font:

![screen shot 2015-08-28 at 12 00 36 pm](https://cloud.githubusercontent.com/assets/33192/9554700/abb588b0-4d7c-11e5-8411-fc660a3f1de8.png)

After:

![screen shot 2015-08-28 at 12 01 07 pm](https://cloud.githubusercontent.com/assets/33192/9554707/b7fe4fd0-4d7c-11e5-8b27-cfa172bab57e.png)

**Comment by yudai** [comment]
To support clients which don't have the font, you can write a fallback family like:

```
font-family = "'DejaVu Sans Mono', monospace"
```

**Comment by haliphax** [comment]
Ack! True enough, I was missing the 'mono' version of the font on that particular machine. Sorry about that! This is wonderful news, though. :) Thanks for the tip re: fallback fonts, too.

**Comment by yudai** [comment]
Great :+1:

The profile file will be merged into the config file in the next release, so please note that you need to modify your configuration file. The new format of the config file is explained here:
https://github.com/yudai/gotty#config-file

**Comment by yudai** [comment]
@haliphax Btw, you can provide a custom css to gotty, so you can use a web font as well. This solution may be useful when you don't want to install a font to your client.

In `~/.gotty`, 
```
preferences {
    font_family = "'Source Code Pro', sans-serif"
    user_css = "https://fonts.googleapis.com/css?family=Source+Code+Pro"
}
```

**Comment by haliphax** [comment]
Ah, awesome! Thanks -- that's exactly the kind of thing I'm looking to do. :)
