### ISSUE TITLE
gotty does not work properly under firefox 64.0

### ISSUE THREAD

**Issue by olivewind** [yudai/gotty#236]
### What version of GoTTY are you using (`gotty --version`)?
gotty version 1.0.1

### What operating system and browser are you using?
Mac os 10.14.1
Firfox 64.0 

### What did you do?

set the '--once' option, just like:

`gotty --address 0.0.0.0 --port 9091 --w --once  docker exec -it b4598916268f sh`

### What did you expect to see?
Gotty Can be work normally at firefox 64.0

### What did you see instead?
everything works fine under Chrome
![image](https://user-images.githubusercontent.com/17901361/50884974-5f7fc580-1427-11e9-8478-88d80771b735.png)

but can't work under Firefox 64.0
![image](https://user-images.githubusercontent.com/17901361/50885041-9524ae80-1427-11e9-8a4f-684f354f4bc3.png)

![image](https://user-images.githubusercontent.com/17901361/50885093-b4bbd700-1427-11e9-994a-d821947ba97b.png)

I guess it is caused by the code below， but I don't know how to fix it
![image](https://user-images.githubusercontent.com/17901361/50885309-4a576680-1428-11e9-89c1-38e9aee067fe.png)

# When file a new feature proposal

**Comment by mateuszkwiatkowski** [comment]
Hello,
we're experiencing the same behavior under Firefox 64. Chrome, Edge and Safari work fine.

**Comment by mateuszkwiatkowski** [comment]
It is `--once` and/or `--max-connections 1` flags that broke the gotty in Firefox for us. For some reason Firefox establishes two connections to gotty:

```
2019/02/08 13:54:26 read tcp 127.0.0.1:40332->127.0.0.1:43213: use of closed network connection
2019/02/08 13:54:26 Connection closed: 127.0.0.1:43213, connections: 1/5
2019/02/08 13:54:36 New client connected: 127.0.0.1:54234
2019/02/08 13:54:36 Command is running for client 127.0.0.1:54234 with PID 4421 (args="bash -l"), connections: 2/5
```

After removing `--once` and bumping `--max-connections` it works when opened directly in Firefox, but is still broken when loaded in iframe.

**Comment by sctlee** [comment]
Hi there,
Is there updates?  This problem also occurs in Firefox 65 66...

**Comment by sctlee** [comment]
https://github.com/DaoCloud/gotty/commit/1e03cc863be22003635c4a61b7b9f2b5b8df4cf7

After I update hterm to v1.84, it works!
