### ISSUE TITLE
integrating with gotty programmatically

### ISSUE THREAD

**Issue by horacimacias** [yudai/gotty#247]
Is there any way to use gotty programmatically from another application?

For example, I want to execute my application but also be in control as to what the user can type in or see.
Imagine I want to _gotty ssh user@server.com_ but I want to hide certain things from the user (e.g. welcome banner) or I want to automatically type certain commands on behalf of the user without them seeing it.
Any suggestions on how to achieve this or am I totally missing how gotty works?

**Comment by horacimacias** [comment]
rephrasing my example, it looks like gotty executes the command every time somebody connects to the web server.
I want to do a similar thing but I will be running the terminal command and then after I want to use gotty to be my PTY-to-web bridge.
This way I can hide things or even execute commands "blindly" without gotty even running, and only start gotty once my application is at the right stage.

**Comment by ryazo** [comment]
You'd have to parse and exclude.

**Comment by horacimacias** [comment]
thanks. I started tinkering with it and looks like I'm getting somewhere now, thanks!

**Comment by jasondeutsch** [comment]
@horacimacias Is this issue still open?

**Comment by horacimacias** [comment]
it was more of a question than an issue but I guess this can be closed.

In my case, in case this helps anybody, I ended up wrapping my "final program" into something that suppresses all output until the "final program" is at the right stage.

Then I use gotty and the wrapper, so that the end user will only "see" what my wrapper allows to be shown to the user. Everything else my wrapper does not even "let through" to gotty so gotty does not show to the user.
