### ISSUE TITLE
Duplicating the command for each client

### ISSUE THREAD

**Issue by Typositoire** [yudai/gotty#25]
I've ran into this while showing this tool to my collegue. When ever I would run the command `kitchen converge` The first few people to connect are actually good, but then at some point every refresh/new connection cause the command the be ran gain.

EDIT: it seems to stop at 2... The first ps is at start with me watching, then the second one is after my collegue joined.

![Example](http://oi59.tinypic.com/24eauu0.jpg)

**Comment by yudai** [comment]
Yes, currently that is the expected  behaviour. Every client connected to gotty gets a new process of the command you provided As described in the README, you can use tmux or gnu screen when you want share a single process with the other clients.

I have a plan to implement a simple pty shareing to gotty, however using tmux is a solid and reliable way to share your view for now.

**Comment by Typositoire** [comment]
Ohhh I got the part where it said you could not share with multiple people but I failed to understand that it would create a new instance of the command. Thanks for the explaination!!!
