### ISSUE TITLE
Set the HTML title to something more descriptive than just "GoTTY"

### ISSUE THREAD

**Issue by niko** [yudai/gotty#28]
Suggestion: "GoTTY - #{command} (#{hostname})"

**Comment by haliphax** [comment]
Or a command line option to pass the title (perhaps with tokens)?

**Comment by yudai** [comment]
Sounds good. I'll add a format option.

**Comment by kevintraver** [comment]
👍

**Comment by yudai** [comment]
The current pre-release (master HEAD) shows   "GoTTY - #{command} (#{hostname})" in the window title. You can specify the format of window titles by providing `--window-format` option.

Let me know if there are any other parameters that can useful for window titles.
