### ISSUE TITLE
Disable Zoom

### ISSUE THREAD

**Issue by collinmccarthy** [yudai/gotty#289]
Is it possible to disable zoom entirely? I'm sharing the output with a bunch of people and if one person zooms in or out so does my window. I'd rather just setup the window to look right on a normal monitor and force people to live with that layout and size. I tried the `--width` and `--height` options but that doesn't help, you can still zoom. I also tried setting `ctrl_plus_minus_zero_zoom = false` but that just changes the keybindings. 

Thank you.

**Comment by collinmccarthy** [comment]
It seems like this should be possible with the `keybindings` but I can't get it working. I tried setting the following in my `.gotty` config file:
```
keybindings = {
"Ctrl-Plus" = "CANCEL"
"Ctrl-Minus" = "CANCEL"
"Ctrl-Zero" = "CANCEL"}
```
as well as changing `CANCEL` to `PASS` and trying the keybindings as `Ctrl+KP_PLUS`, `Ctrl+KP_MINUS`, `Ctrl+Zero` as per the keybindings [here](https://chromium.googlesource.com/apps/libapps/+/master/hterm/js/hterm_parser_identifiers.js) and the actions [here](https://chromium.googlesource.com/apps/libapps/+/master/hterm/doc/KeyboardBindings.md).

If anyone knows what I'm doing wrong, or has any other ideas, that would be much appreciated!

Edit: My issues using `--width` and `--height` with tmux are probably related to #243 . And to be clear, I have a new tmux session for each client, but when one person changes the font size / resizes the window using these commands all of the client windows get smaller/larger (they start with different sizes and stay different, they just both increase/decrease when one person does so).

**Comment by collinmccarthy** [comment]
Okay a couple of things:
1. When one client changes font size / zooms out the other clients DO NOT see it. The reason I thought they were seeing it is because I was testing this in a single browser session, and in that case resizing one `gotty` tab resized any other ones running in the same browser. When using a second computer connected to the same `gotty` server, resizing one did not resize the other, great!
2. The only way I was able to get `tmux` working the way I wanted to was to launch a new session for every user. This only works if you can somehow share the output in some way other than shared tmux sessions. In my case I could monitor GPU stats by outputting them to a file and then having every client watch / tail the output of that file. And I could monitor CPU stats using `glances` configured in a client/server model, and have every user run their own `glances` client in `tmux`.

This is my script `start_tmux.sh` to setup new `tmux` sessions, using `htop` as a simple example here. I simply call this with `gotty start_tmux.sh` and every client gets their own `tmux` window that they can zoom in and out of as they need to. I may look into using `gotty -w` and `tmux attach-session -r` if I setup multiple windows, as that should allow clients to change windows and detach, but not enter any other commands (and the `gotty` connection closes when the `tmux` session is destroyed on detach).

```bash
#!/bin/bash

# Get a new session
SESSION=0
NEW_SESSION_OUTPUT=$(tmux new-session -d -s $SESSION 2>&1)

while [ -n "$NEW_SESSION_OUTPUT" ]; do
    SESSION=$(($SESSION+1))
    NEW_SESSION_OUTPUT=$(tmux new-session -d -s $SESSION 2>&1)
done

# Configure tmux as needed
tmux send-keys -t $SESSION:0 htop C-m

# Attach then automatically destroy when unattached
tmux attach-session -t $SESSION \; set-option -t $SESSION:0 destroy-unattached on
```

**Comment by perguth** [comment]
Awesome! Thank you @collinmccarthy for sharing!
