### ISSUE TITLE
32bit version

### ISSUE THREAD

**Issue by tbox1911** [yudai/gotty#29]
Hi,

Is it possible to have a 32 bit binary version in Release archive ?

Thanks

**Comment by yudai** [comment]
Hi, thank you the request.
I'll add 32bit build soon.

**Comment by yudai** [comment]
Done.

Could you test it on your environment? I don't have one myself.

**Comment by tbox1911** [comment]
You made it ! :)
run smoothly on Debian Strech / Ubutnu Trusty
thank you very much, I found you tool very useful !
Best regards

**Comment by tbox1911** [comment]
Hi,

just to add another way of sharing terminal (like tmux) but with screen
command.

- first, start the session, named GOTTY, with command top
> screen -dmS GOTTY top

- then start Gotty
>gotty screen -x GOTTY

- you can interact with the GOTTY session from local terminal by:
>screen -x GOTTY

Hope it helps ;)

Best Regards

**Comment by yudai** [comment]
Thanks!
