### ISSUE TITLE
Use standard VGA colors or allow for custom palette

### ISSUE THREAD

**Issue by haliphax** [yudai/gotty#30]
https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

As I mentioned in another issue, I'm using GoTTY as a bridge for my telnet BBS, but the colors are a bit off for VGA textmode artwork.

https://oddnetwork.org/bbs/

Awesome work, anyway! I really appreciate the app.

**Comment by yudai** [comment]
Hi, thank you for the feed back.
What colors are not shown?

**Comment by haliphax** [comment]
It doesn't seem like any colors are missing, per se, just that they don't quite look like the Linux console default colors. It's certainly not a big deal. For the artwork, I think the font specification would be more important, as some characters don't appear to be true monospace:

![screenshot from 2015-08-22 08 58 44](https://cloud.githubusercontent.com/assets/745888/9424298/1284bd1a-48ad-11e5-8024-c0f90c704757.png)

**Comment by yudai** [comment]
Got it. This issue should be solved by the config file support. hterm has properties for ASCII colors.

**Comment by haliphax** [comment]
Cool, thanks!

**Comment by yudai** [comment]
Now you can customize the color pallet by using `color-palette-overrides` in your profile file.
