### ISSUE TITLE
"Failed to upgrade connection" sometimes on Chrome

### ISSUE THREAD

**Issue by Moter8** [yudai/gotty#31]
```
2015/08/19 20:56:32 New client connected: <my ip>:26736
2015/08/19 20:56:32 Failed to upgrade connection
```

Getting this error sometimes, only on Chrome. Firefox runs it well. 
Client shows only a blank page. 
Yesterday I had tried it out already and everything was fine.

**Comment by haliphax** [comment]
Do you have a proxy sitting in front of GoTTY, or is it raw? Just curious, since I was having this issue, as well, but fixed it with some nginx configuration settings. Of course, I was constantly experiencing the error -- it wasn't intermittent.

**Comment by yudai** [comment]
Is that possible to provide the command you ran?
If you are using a proxy as @haliphax mentioned, let me know that too.

**Comment by Moter8** [comment]
I ran both `gotty htop -p "8080"` and the one to start gotty with tmux from
the readme.

Nginx is running on the machine but gotty is not getting proxied by it.

**Comment by yudai** [comment]
Thanks. Unfortunately, I have no idea about what's the cause but it's a websocket related issue.

**Comment by Moter8** [comment]
@yudai Ooh, I think I got the cause of this now. It's probably caused by Cloudflare. I have it only running on @ and only there it doesn't work. Tested on both Chrome and Firefox.

![0](https://i.imgur.com/5nYfK4H.png)

http://92.222.74.40:8080/ OK
http://znc.moter8.xyz:8080/ OK
http://moter8.xyz:8080/ KO

**Comment by Moter8** [comment]
https://support.cloudflare.com/hc/en-us/articles/200169466-Can-I-use-CloudFlare-with-websockets-

>WebSockets are currently only available for Enterprise customers, but will be available for other plan levels in the future.

>All other customers -- Business, Pro, and Free -- should create a subdomain for Websockets in their CloudFlare DNS and disable the CloudFlare proxy ("grey cloud" the record in CloudFlare DNS Settings).

**Comment by k0l0r3k99** [comment]
I tcpdumped traffic before CloudFlare and after CloudFlare. CF removes only "Upgrade: websocket", other data are unchanged. Could gotty ignore "Upgrade: websocket"? Another way to fix is use nginx proxy and add header with upgrade.

Edit: use nginx doesn't resolve this. I've error: "Failed to authenticate websocket connection: websocket: close 1006 unexpected EOF". In JS, new WebSocket("wss://cloudflare/gotty/ws").onOpen is not called.

**Comment by rajeget** [comment]
For NGINX please see my page https://github.com/rajeget/websocket-nginx/ , it works 

Let me know if that works for cloudfare as well .
