### ISSUE TITLE
feature request: copy and paste

### ISSUE THREAD

**Issue by hugoeustaquio** [yudai/gotty#32]
Copy and paste wold be an awesome improvement!

Thank you!

**Comment by yudai** [comment]
Which platform are you using?

If it's OSX and chrome;
To copy, you can just select text and it'll send to your clipboard automatically.
And you can use Command+V to paste

**Comment by hugoeustaquio** [comment]
Sorry, I'm using slackware linux 64 bits with firefox.
I thought it was a missing feature, but I tested now on google chrome and it seems to work. It's not a feature request, just  a firefox bug. And it's just "paste" that doesn't work, not "copy".

**Comment by hugoeustaquio** [comment]
I tried "shift+insert", "middle-click" and "ctrl+v". Control+v makes gotty print "^M", as follows:

bash-4.3$ ^M 
bash: $'\r': command not found

 My system use a UTF-8 encode, maybe it's something related. I will start to use some WebKit based browser, thanks!

**Comment by Arno0x** [comment]
I'm experiencing the same issue under Firefox 39.0.3 on windows and OSX. It's kindof weird it doesn't work with GoTTY, where it works with GateOne (which uses pretty much the same principle).

**Comment by yudai** [comment]
What about using these options?
https://github.com/yudai/gotty/blob/master/.gotty#L66-L67

**Comment by jungle-boogie** [comment]
Hi @yudai,

The problem with ctrl+c is that if you have `-w` enabled, this will close the connection.

test it out: `gotty -w top`

**Comment by yudai** [comment]
@jungle-boogie As for copy on Chrome, it seems like just selecting text by your mouse is the best way to copy.
However, it looks firefox has some issue around copy&paste. Let me look into it.

**Comment by jungle-boogie** [comment]
Hi @yudai,

Yes, your observations with firefox are correct regarding copying text; however, ctrl-c with the `-w` will still close the connection in Chrome, just as I would expect.

**Comment by wapsi** [comment]
Just tested in Firefox and looks like ctrl+v is working just fine but ctrl+c isn't. The "text copied icon" appears on the screen but it's not really copying (old data remains in clipboard). Tested on CentOS 7.1, Firefox ESR: firefox-38.2.1-1.el7.centos.x86_64. Both paste & copy is working in Chrome though.

I've configured following lines in config file:
  ctrl_c_copy = true
  ctrl_v_paste = true
and Gotty has been executed using -w argument as well.

**Comment by tjdett** [comment]
Seeing the same problem with Firefox 43 on Fedora Linux. Specifically:
 * highlight-based copying doesn't copy anything to the clipboard (either of them)
 * highlight-then-hold while using <kbd>ctrl + shift + c</kbd> does copy to clipboard
 * <kbd>ctrl + shift + v</kbd> doesn't paste

Tested with the defaults (`ctrl_c_copy = false` & `ctrl_v_paste = false`) and after verifying the functionality works in Chrome 47.

**Comment by brmzkw** [comment]
Is someone working on a fix?

**Comment by yudai** [comment]
I'm not working on this issue right now.

PR is welcome.

**Comment by azlux** [comment]
Hi, if you use this part of the conf, you will be able to use the default clipboard manager of firefox. In this case, you need to press Ctrl+C and Ctrl+V like normal text , nothing will be catch by hterm.
```
copy_on_select = false
use_default_window_copy = true
clear_selection_after_copy = false
ctrl_c_copy = true
ctrl_v_paste = true
```

**Comment by yudai** [comment]
Now the terminal library is default to xterm, which should support copy&paste on Firefox.
Please reopen if the issue still exist.

**Comment by Piping** [comment]
@yudai I try to copy text to system clipboard when I am under a tmux session.

The copy does not work in both chrome and Firefox. Any help?

In tmux, I have set `set -g clipboard`
