### ISSUE TITLE
Allow clients to specify commnd

### ISSUE THREAD

**Issue by yudai** [yudai/gotty#33]
I know, it's dangerous enough.

## Option 1
Allow send only arguments like run `gotty --permit-arguments tailf` then, access `http://server.exmple.com:8080/%2Fvar%2Flog%2Fsyslog` (/var/log/syslog).
(Need to take care of shell meta characters not to permit using pipe and redirects)

## Option 2
Freedom mode like `gotty --freedom` then, access `http://server.example.com:8080/tailf+%2Fvar%2Flog%2Fsyslog`.

**Comment by jay2u** [comment]
You could also just run
`gotty -w bash --login`
of course :-)

Even more dangerous :-O

But I can see the point of having the convenience of specifying the command in the URL.

**Comment by niko** [comment]
I think passing multiple commands via the command line would be too much. I would like to see a simple config file, perhaps similar to Foremans Procfile format:

```
tailaa: tail -f /var/log/apache/access.log
tailae: tail -f /var/log/apache/error.log
```

And now just the two commands can be executed by accessing /tailaa and /tailae.

**Comment by haliphax** [comment]
@niko's idea is solid, though that could be just another feature if you're dead set on allowing a full command to be specified, as well.

**Comment by Arno0x** [comment]
I found myself this idea interesting enough. So I've written and am about to release a PHP wrapper to GoTTY that allows for this kind of things and more. I'll keep Yudai posted as well as this issue thread.

**Comment by Arno0x** [comment]
Out of interest, here is TermGate, a GoTTY wrapper in PHP, which might suit your needs: https://github.com/Arno0x/TermGate

**Comment by yudai** [comment]
Awesome :+1: 
Now I feel like I should keep gotty itself as simple as possible. Other tools like @Arno0x 's one can solve the demand.

**Comment by haliphax** [comment]
Good on ya, @Arno0x !

**Comment by wapsi** [comment]
Hi, I accidentaly created a duplicated issue about this (#53) although I've suggested delivering client information in addition to program arguments:

I would be nice if it's possible to deliver parameters or information about the client to the command to be executed when client connects to gotty.

Example1:
gotty /opt/cmd
http://hostname:8080/?arg1=foo&arg2=bar => gotty will execute /opt/cmd arg1=foo arg2=bar

In terms of security reasons it would be reasonable if it's possible to limit what arguments should be delivered and what data could be into them (only digits / only A-Z)?

Example2:
gotty /opt/cmd %CLIENT_IP_ADDRESS%
192.168.1.10 connects to http://hostname:8080/ => gotty will execute /opt/cmd 192.168.1.10

**Comment by moul** [comment]
#64 is fixing this issue
