### ISSUE TITLE
fatal error: runtime: bsdthread_register error

### ISSUE THREAD

**Issue by mathieux51** [yudai/gotty#340]
### What version of GoTTY are you using (`gotty --version`)?
I installed the latest version with brew and this is what I get when I run the above command:

```sh
gotty --version
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x38fc7b, 0x21)
        /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0x7ff7bfeff070 sp=0x7ff7bfeff050
runtime.goenvs()
        /usr/local/go/src/runtime/os_darwin.go:88 +0xa0 fp=0x7ff7bfeff0a0 sp=0x7ff7bfeff070
runtime.schedinit()
        /usr/local/go/src/runtime/proc.go:450 +0x9c fp=0x7ff7bfeff0e0 sp=0x7ff7bfeff0a0
runtime.rt0_go(0x7ff7bfeff118, 0x2, 0x7ff7bfeff118, 0x0, 0x1000, 0x2, 0x7ff7bfeff3d0, 0x7ff7bfeff3d6, 0x0, 0x7ff7bfeff3e0, ...)
        /usr/local/go/src/runtime/asm_amd64.s:145 +0x14f fp=0x7ff7bfeff0e8 sp=0x7ff7bfeff0e0
```

### What operating system and browser are you using?
I'm using macOS Monterey 12.5 and Firefox is my default browser.

### What did you do?
I installed gotty with `brew install yudai/gotty/gotty` and try to run `gotty top`

### What did you expect to see?

I expected to see `top` command in my browser.

### What did you see instead?

For everything I run I see:

```
fatal error: runtime: bsdthread_register error
runtime stack:
runtime.throw(0x38fc7b, 0x21)
        /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0x7ff7bfeff070 sp=0x7ff7bfeff050
runtime.goenvs()
        /usr/local/go/src/runtime/os_darwin.go:88 +0xa0 fp=0x7ff7bfeff0a0 sp=0x7ff7bfeff070
runtime.schedinit()
        /usr/local/go/src/runtime/proc.go:450 +0x9c fp=0x7ff7bfeff0e0 sp=0x7ff7bfeff0a0
runtime.rt0_go(0x7ff7bfeff118, 0x2, 0x7ff7bfeff118, 0x0, 0x1000, 0x2, 0x7ff7bfeff3d0, 0x7ff7bfeff3d6, 0x0, 0x7ff7bfeff3e0, ...)
        /usr/local/go/src/runtime/asm_amd64.s:145 +0x14f fp=0x7ff7bfeff0e8 sp=0x7ff7bfeff0e0
```

**Comment by Andy-ch** [comment]
I have this issue as well

**Comment by sunboshan** [comment]
Any update for this issue? On Monterey, brew installed version is not working with above error.

**Comment by ganglio** [comment]
Same here. Monterey 12.6.

**Comment by tigattack** [comment]
The latest release is built on Go 1.9. It needs to be built on =>1.11 to fix this: https://github.com/golang/go/wiki/MacOS12BSDThreadRegisterIssue

This works https://github.com/sorenisanerd/gotty

**Comment by mathieux51** [comment]
> This works https://github.com/sorenisanerd/gotty

Indeed it does 👍

**Comment by mathieux51** [comment]
> This works https://github.com/sorenisanerd/gotty

Indeed it does 👍
