### ISSUE TITLE
Midnight Commander ... frozen on Qnap with Gotty

### ISSUE THREAD

**Issue by nephaste** [yudai/gotty#35]
Thanks for this apps, run fine on Qnap NAS QPKG is available here 

http://forum.qnap.com/viewtopic.php?f=320&t=113304

but i wonder why Midnight commander stay frozen.. not sure how to debug

**Comment by yudai** [comment]
Hi,
Thank you for the QNAP support. Unfortunately I don't have a QNAP at my home, so I myself cannot support you for the issue.

**Comment by yudai** [comment]
Closing as no activities last week. Please reopen if this issue still exists.

**Comment by nephaste** [comment]
seems working in 0.0.10   ;)

just need export TERM=xterm  

thanks a lot for your great work

**Comment by yudai** [comment]
:+1:
