### ISSUE TITLE
Add Linux_armhf release

### ISSUE THREAD

**Issue by Arno0x** [yudai/gotty#41]
Could it be possible to add Linux ARMHF (Raspberry Pi) releases ?

Thanks !

**Comment by yudai** [comment]
Added ARM to the release. As I'm not sure the `arm` architecture is what you want, let me know when it doesn't work on Raspberry Pi. Unfortunately, I don't have one.

**Comment by Arno0x** [comment]
Works like a charm on Raspberry Pi 2( which is ARM architecture). So that's exactly what I needed ! Many thanks !

**Comment by yudai** [comment]
Glad to hear that! Thanks!
