### ISSUE TITLE
Windows binary/release

### ISSUE THREAD

**Issue by dheerajbhaskar** [yudai/gotty#45]
1. Will this ever work with Windows?
2. If it can, is windows support on the dev path?
3. What could a "regular Joe" user do to use this on windows right now? Using it in docker is the simplest option?

PS: I'm excited :smile:

**Comment by yudai** [comment]
Hi,

1. Unfortunately, Gotty doesn't support Windows now.
2. I'm not a serious Windows user for development stuff, so I myself have no urgent need for Windows support 
3. Docker or Vagrant?

**Comment by dheerajbhaskar** [comment]
Thanks @yudai for the reply

1. 2. Okay
3. I did mean Docker, because, it will quickly give a linux environment without the hassles of a complete VM.

We can continue the discussion, but I shall close the issue because we've narrowed down the solutions sufficiently.
