### ISSUE TITLE
once option doesn't kill child processes

### ISSUE THREAD

**Issue by swills** [yudai/gotty#46]
For me, if I run `gotty --once -w vim` then connect in the browser, then close the browser tab, I find that gotty is still running.

**Comment by yudai** [comment]
Thank you for the report.
I just succeeded to reproduce the issue. Give me a little bit time to fix it.

**Comment by yudai** [comment]
Pushed a patch for this issue. Please try the pre-release.

**Comment by swills** [comment]
Thanks for the quick response! I tested and this seems to fix it. Thanks for the update!
