### ISSUE TITLE
Consider change gotty name, there is another gotty and older software

### ISSUE THREAD

**Issue by jetm** [yudai/gotty#47]
Hello,

I was searching for this handy software and this first link http://gotty.io/ appeared.

Could you consider to change name to avoid future confusion like this one? http://gotty.io is older than this project.

Thanks.

**Comment by yudai** [comment]
Yes, I've been thinking a new name of gotty since I realized there had been another gotty, but unfortunately I've never come up with a good and simple enough name yet.

Somethings I came up with:

* ttygo
* g0tty
* yagt
* shtty

Proposal is welcome :+1:

**Comment by jetm** [comment]
I was thinking this gotty is related to terminal (CLI, TTY) and web (WWW, HTTP). Some combinations could be:
* twi (**T**erminal **W**eb **I**nterface)
* thi  (**T**erminal **H**ttp **I**nterface)
* t2w (**T**erminal **T**o **W**eb)
* t2h (**T**erminal **T**o **H**ttp)

or some combinations from your name:
* yai
* dai
* saki

**Comment by stonevil** [comment]
gitty. from kitty. fun one :-)

**Comment by TheOneValen** [comment]
goterm

**Comment by haliphax** [comment]
I think shtty is hilarious, and gets my vote. +1!

**Comment by jetm** [comment]
Seeing 'shtty' as suggestion, I would not like to think in 'shitty'.

**Comment by haliphax** [comment]
It's tongue-in-cheek.

**Comment by booyaa** [comment]
A quick check on github:
- [goterm](https://github.com/search?utf8=%E2%9C%93&q=goterm) (3 repos with the same name)
- [yagt](https://github.com/search?utf8=%E2%9C%93&q=yagt) - (3 repos)
- [shtty](https://github.com/search?utf8=%E2%9C%93&q=shtty) - (1 repo)

My $0.02 I think you should hang onto the name, okay the guy has gotty.io, but look at how many stars 5k+, watches 164, forks 185 vs theirs 7, 4 and 4 on github.

Your software has a greater reach. Just needs more blogs and cross references in Github to improve it's ranking in search engines.

If you need a new name, how about [gophertty](https://github.com/search?utf8=%E2%9C%93&q=gophertty) or [gopherterm](https://github.com/search?utf8=%E2%9C%93&q=gopherterm)?

**Comment by jetm** [comment]
It seems is not obvious, but sometimes figure out new names is hard. Thinking on some inspiration sources, e.g:
* A rare unknown/unused English word with some relation to the project or creator.
* Using a tool to combine known words to create new one, like: http://unique-names.com/word-mixer.php.

**Comment by haliphax** [comment]
The shtty repo is just a README with a single line of text, by the way -- no code, and it hasn't been touched in 8 months. That being said, yeah, I'd just stick with 'gotty'.

**Comment by jetm** [comment]
Stick with 'gotty' will bring problems for software packagers because will exist two binaries with same name. Each binary are from different projects.

**Comment by oneumyvakin** [comment]
Looks like http://gotty.io is dead, so not a problem any more.

**Comment by yudai** [comment]
Thanks for the information. Closing.
