### ISSUE TITLE
OS X 10.10.5, Safari 8.0.8 cannot handle basic authentication

### ISSUE THREAD

**Issue by stonevil** [yudai/gotty#48]
OS X 10.10.5, Safari 8.0.8 issue: "failed: Unexpected response code: 401"

Work very well in OS X 10.10.5, Firefox 40.0.3

**Comment by yudai** [comment]
Hi, thank you for the report.

Could you share the command you provided to gotty when you got the error?
Let me know the output of `gotty -v` as well.

Thanks!

**Comment by stonevil** [comment]
gotty -v output:
gotty version 0.0.7

.gotty file

// Listen at port
port = "9111"

// Enable basic authentication
enable_basic_auth = true

// Username and password of basic authentication (user:pass)
credential = "someuser:somepass"

// Enable TSL/SSL by default
enable_tls = true

// Title format of browser window
title_format = "GoTTY - {{ .Hostname }} {{ .Command }} ({{ .Hostname }})"

// hterm preferences
preferences {
	ctrl_c_copy = true
	ctrl_v_paste = true
	cursor_blink = true
	font_size = 12
	font_family = "'Menlo Regular',  monospace"
	east_asian_ambiguous_as_two_column = false
}

**Comment by stonevil** [comment]
when I enable SSL/TSL in config file I get issue https://github.com/yudai/gotty/issues/49

**Comment by yudai** [comment]
Thanks.

It seems like when basic auth is enabled, safari fails to establish a websocket. I'll look for a workaround.

**Comment by yudai** [comment]
Pushed a fix to the master branch. Now you can use `-c` option with Safari.
However, Safari doesn't support self-signed certificates for WebSockets. If you need TLS connection on safari, you must get a valid certificate.

**Comment by yudai** [comment]
The previous fix was incomplete and has been reverted.

Now feeling like I don't need Basic Auth for safari....

**Comment by yudai** [comment]
Ok... fixed anyway...
