### ISSUE TITLE
Cannot set Preference color-palette-overrides

### ISSUE THREAD

**Issue by TheOneValen** [yudai/gotty#50]
When setting 'color-palette-overrides' I get the following error in the javascript debug window (firefox)

    [15:34:58.042] "Preference color-palette-overrides is not an array or object: {'0':'#073642','1':'#dc322f','2':'#859900','3':'#b58900','4':'#268bd2','5':'#d33682','6':'#2aa198','7':'#eee8d5','8':'#002b36','9':'#cb4b16','10':'#586e75','11':'#657b83','12':'#839496','13':'#6c71c4','14':'#93a1a1','15':'#fdf6e3'}"

In my .gotty file I intered

    color_palette_overrides = "{'0':'#073642','1':'#dc322f','2':'#859900','3':'#b58900','4':'#268bd2','5':'#d33682','6':'#2aa198','7':'#eee8d5','8':'#002b36','9':'#cb4b16','10':'#586e75','11':'#657b83','12':'#839496','13':'#6c71c4','14':'#93a1a1','15':'#fdf6e3'}"

Within the Preference object.

**Comment by yudai** [comment]
Thank you for the report.
Confirmed that a bug. I'll fix it by the next release.

**Comment by yudai** [comment]
@TheOneValen meanwhile, you can writ like below:

```
  color_palette_overrides = ["#073642","#dc322f","#859900","#b58900","#268bd2","#d33682","#2aa198","#eee8d5","#002b36","#cb4b16","#586e75","#657b83","#839496","#6c71c4","#93a1a1","#fdf6e3"]
```

**Comment by TheOneValen** [comment]
that works, thank you!

**Comment by haliphax** [comment]
Thank you for this. I was trying to figure out how I would specify the colors for the "default 16" to make them mirror the original IBM PC VGA stuff, and this will do the trick nicely.

**Comment by TheOneValen** [comment]
I now have a nicely solarized (dark) gotty. Do you intent to start a wiki or some other form of documentation. I could put the configuration there for other people to use.

**Comment by yudai** [comment]
I'm glad to hear you got a good color scheme :+1: 

I'm afraid I'm not going to open the wiki pages on this repo for now because unfortunately I don't have much time to manage them (I might change my mind in the feature).

**Comment by yudai** [comment]
Now hterm preferences are handled in a better way.
