### ISSUE TITLE
Unprintable Characters disconnect Gotty

### ISSUE THREAD

**Issue by TheOneValen** [yudai/gotty#52]
When doing dumb stuff like cat /dev/random or cat on binaries which yield unprintable characters (and may screw up a terminal under "normal" circumstances ) lead to a disconnection. This is especially bad when byobu (tmux wrapper) runs in the background, which makes reconnection impossible ;-).

I don't know if this is fixable, but I thought worth mentioning.

**Comment by haliphax** [comment]
I noticed this, as well, when using certain terminal sequences -- specifically, the ones that coerce terminal encoding, like `\x1b%@`, `\x1b(U`, and `\x1b%G`.

**Comment by yudai** [comment]
Thanks for the report.
It was a bug and has been fixed in the current pre-release :+1:
