### ISSUE TITLE
Ability to deliver parameters and client info via URL/POST/cookie or similar

### ISSUE THREAD

**Issue by wapsi** [yudai/gotty#53]
I would be nice if it's possible to deliver parameters or information about the client to the command to be executed when client connects to gotty.

Example1:
**gotty /opt/cmd**
http://hostname:8080/?arg1=foo&arg2=bar => gotty will execute **/opt/cmd arg1=foo arg2=bar**

In terms of security reasons it would be reasonable if it's possible to limit what arguments should be delivered and what data could be into them (only digits / only A-Z)?

Example2:
**gotty /opt/cmd %CLIENT_IP_ADDRESS%**
192.168.1.10 connects to http://hostname:8080/ => gotty will execute **/opt/cmd 192.168.1.10**

**Comment by yudai** [comment]
Hi, thank you for the feedback.
There is a similar issue #33 . Could you move to this issue?
