### ISSUE TITLE
Support for URL links

### ISSUE THREAD

**Issue by wapsi** [yudai/gotty#54]
It would be nice if there are URLs in the screen the gotty / JS could convert them into links which will open into new window.

The code should be aware if the URL continues into the next line like (typical situation in chat window):

_SomeNick:_ Check this out: **http://www.foo.com/bar/dir/something/inde
x.php** that's so cool!
_OtherNick:_ yes!

**Comment by yudai** [comment]
Hi, thank you for the feedback.

This feature requires hterm enhancement. So it takes time to implement.

**Comment by yudai** [comment]
It's now supported in the master branch, as a part of xterm integration.

**Comment by ghost** [comment]
> It's now supported in the master branch, as a part of xterm integration.

Can you give an example of this behavior?
