### ISSUE TITLE
Once and reconnect can not work together

### ISSUE THREAD

**Issue by yank1** [yudai/gotty#56]
Gotty is very awesome.

When I set ' --once' , the console can not reconnect.
So I cannot use gotty in a  unstable network with once feature. 

Thanks .

**Comment by yudai** [comment]
Hi. Thank you for the feed back.
The `--once` option is literally allow a client to access the server only once. So you cannot use with the `--reconnect` option with it. If you need to keep a session, please consider using terminal multiplexer like tmux.

**Comment by yudai** [comment]
Closing as no recent activities. Please reopen when needed.
