### ISSUE TITLE
Alt key is being mapped to meta key

### ISSUE THREAD

**Issue by jsageryd** [yudai/gotty#59]
The alt key ("option key") on OS X gets mapped to the meta key, making it impossible to write e.g. "@" (on my keyboard layout "@" is alt+2) and a range of other characters (©, £, $, ∞, §, |, [, ], etc.).

**Comment by yudai** [comment]
Hi @jsageryd,

I'm not sure this helps, but could you try configuration (`~/.gotty`) described below?

```
preferences {
    alt-sends-what = "browser-key"
}
```

or

```
preferences {
    alt_is_meta: true
}
```

By the way, what type of keyboard are you using? Just curious.

**Comment by jsageryd** [comment]
Context
```
$ gotty --version
gotty version 0.0.10
```

This works:
```
preferences {
  alt-sends-what = "browser-key"
}
```

This does not work:
```
preferences {
  alt_is_meta = true
}
```

Problem solved! Is there any way to supply this as a cmdline option?

**Comment by yudai** [comment]
Sorry, the correct syntax was `alt_sends_what = "browser-key"` (underscores).
Anyway, I'm glad to hear you can now use your alt key.

It sounds hard to support preferences by command line options because there are too many preferences and some of them needs json objects.

**Comment by yudai** [comment]
Closing as the issue has been solved. As for the command line option support, please create a new issue as a feature request.
