### ISSUE TITLE
When running "clear" and another client attaches, the screen refreshes

### ISSUE THREAD

**Issue by matthiasbeyer** [yudai/gotty#62]
To reproduce:

```
$ gotty tmux new -A -s gotty top
```

Connect via tmux:

```
tmux att -t gotty
```

* Connect to `localhost:8080` to view the terminal in a browser
* Inside tmux, create a new pane and type something
* Now type `clear` to clear the terminal buffer
* Connect with another client
* -> The contents which were just `clear`ed reappear

**Comment by yudai** [comment]
Hi, thank you for the feedback.

I tried to reproduce your issue, but couldn't get it. Let me ask a couple of questions to make your procedure clear.

> Inside tmux, create a new pane and type something
Did you create a new pane with `split-window`?

> Connect with another client
Was this client gotty or tmux?

Thanks!

**Comment by matthiasbeyer** [comment]
> > Inside tmux, create a new pane and type something

> Did you create a new pane with split-window?

Yes.

> > Connect with another client

> Was this client gotty or tmux?

tmux.

**Comment by yudai** [comment]
@matthiasbeyer, I tried to reproduce your issue along the procedure you described. However, I could not see the situation you got in my environment.

**Comment by yudai** [comment]
Closing as no recent updates. Please reopen if you need any updates  to this ticket.
