### ISSUE TITLE
Tittle lost on update

### ISSUE THREAD

**Issue by rgawenda** [yudai/gotty#65]
The tittle tag losses it's initial value when contents are updated.

**Comment by booyaa** [comment]
Are you using a terminal multiplexer like tmux or screen as your gotty command?? I know tmux will rewrite the window title so gotty will probably honour this request.

**Comment by rgawenda** [comment]
No, it's just a grcat, prettifying a running log (using gotty 0.0.10):
Launched it with: `gotty grc tail -f /var/log/rex.log`, and using this .gottyrc

    address = "10.68.30.33"
    port = "443"
    enable_basic_auth = true
    credential = "user:pass"
    enable_tls = true
    tls_crt_file = "/etc/ssl/certs/io.crt"
    tls_key_file = "/etc/ssl/certs/io.key"
    title_format = "Input/Ouput {{ .Hostname }}"
    preferences {
            font_family = "'FreeMono', 'Menlo', 'Terminal',  monospace"
            font-size = 14
    }

**Comment by yudai** [comment]
Hi @rgawenda, thank you for the feedback.
Unfortunately, I could not reproduce your issue in my environment. My assumption is that your `rex.log` file has some escape sequences that updates your terminal title.

**Comment by rgawenda** [comment]
I've done some more research on this, even when it's a very minor annoyance but I think it can be related to the event that is attached to the socket in js (gotty.js:52).
It get's called with a data "2mytittlehere", but later with (I suppose) a ping sets data "1" so the slice gets empty and the case '1' in line 58 doesn't have a break, and continues to case '2' clearing the tittle. I'm trying to setup a go environment to build so I could confirm, but it seems that would need more reading time than I have now (on gentoo).

**Comment by rgawenda** [comment]
I can confirm that issue is resolved adding a break between case '1' and case '2' (but I'm not sure if this breaks anything else).

**Comment by yudai** [comment]
@rgawenda Thanks for debugging and your solution. Fixed the issue in the main branch.
