### ISSUE TITLE
Is there a workaround to make gotty work with ngrok?

### ISSUE THREAD

**Issue by bsapwindows** [yudai/gotty#72]
I currently got "Failed to authenticate websocket connection".

**Comment by jungle-boogie** [comment]
just curious, what would be the usecase for ngrok with gotty?

**Comment by bsapwindows** [comment]
Well, just thought ngrok is a convenient way to cover up server's IP and port number.

**Comment by yudai** [comment]
The error "Failed to authenticate websocket connection" is raised when a client didn't send a valid token to the server. Clients get the token from `/auth_token.js`. Could you confirm you can access this path from your browser?

**Comment by bsapwindows** [comment]
This is what I got in terminal log when I was visiting http://*.ngrok.io/, I didn't see something like `200 GET /auth_token.js`:
```
2015/10/04 15:35:53 127.0.0.1:40099 200 GET /
2015/10/04 15:35:53 [::1]:59006 200 GET /js/hterm.js
2015/10/04 15:35:53 127.0.0.1:40103 200 GET /js/gotty.js
2015/10/04 15:35:54 New client connected: [::1]:59010
2015/10/04 15:35:55 Failed to authenticate websocket connection
2015/10/04 15:35:55 [::1]:59010 101 GET /ws
```

but `http://*.ngrok.io/auth_token.js` is accessible directly from my browser, it returns `var gotty_auth_token = '';` and `[::1]:59012 200 GET /auth_token.js` shows in terminal log.

**Comment by yudai** [comment]
Thanks.
Could you try with `-c "test:test"` and see what's in the `auth_token.js`?

Ngrok might not support websocket connections?

**Comment by bsapwindows** [comment]
Hmm, weird. It worked after I added `-c "test:test"`, but the browser didn't ask for username and password.  I was asked for username and password when I was visiting `/auth_token.js`, and it returns `var gotty_auth_token = 'test:test';`. :confused:

**Comment by yudai** [comment]
Thank you for testing. It looks a really weird situation. Do you have `~/.gotty` file?

**Comment by bsapwindows** [comment]
Just tested v0.0.1 without using config file and v0.0.10 with `-c` and config file, they work as expected, even from Chrome 37.

.gotty:
```
port = "8080"
title_format = "gotty"
preferences {
  background_color = "rgb(16, 16, 16)"
  background_image = ""
  cursor_blink = true
  cursor_color = "rgba(255, 255, 255, 0.5)"
  ctrl_c_copy = false
  ctrl_v_paste = false
  east_asian_ambiguous_as_two_column = false
  font_family = "'DejaVu Sans Mono', 'Everson Mono', 'FreeMono', 'Menlo', 'Terminal', monospace"
  font_size = 11
  foreground_color = "rgb(240, 240, 240)"
  user_css = ""
}
```

**Comment by yudai** [comment]
I installed ngrok (2) to my env and tried running `~/tmp/ngrok http 8080`.
It worked well with my Chrome Version 45.0.2454.101 (64-bit), Safari Version 9.0.1 (11601.2.4) and Firefox 40.0.3 on Mac OS X for both http and https. (gotty itself exposes only http, without the `--tls1 option).
Unfortunately, I could not reproduce your issue on my env. Cache or something?

**Comment by bsapwindows** [comment]
With or without `-c`? With `-c`, it works from my Chrome 45 too. Without it, it will show `Connection Closed`

**Comment by yudai** [comment]
I tried without `-c`. 
Can you connect to your gotty server from your browser without `-c` when you directly access the server?

**Comment by bsapwindows** [comment]
Yes I can.

Could you try this url? [http://5e7850d4.ngrok.io/](http://5e7850d4.ngrok.io/)

**Comment by yudai** [comment]
It worked perfectly from my side

**Comment by bsapwindows** [comment]
...OK, that's so weird... I asked a friend to test for me, he says it's working as well.

I guess it's because of my own computer issue? But `-c` can fix it. No idea why.

Thanks anyway.

**Comment by booyaa** [comment]
@bsapwindows i know this closed, but re: hiding server's ip and port num. What using nginx's proxy pass? It's what I'm using to expose gotty listening on a private address to nginx which is on a public address. Give me a shout if you want to see the config, @yudai provided one in another issue.

**Comment by bsapwindows** [comment]
@booyaa Thank you for your kindness. :)
Well, I do believe using a reverse proxy will achieve the same goal. But considering the need is temporary , ngrok.io is publicly available and it supports HTTPS without additional configuration, I think ngrok is better for me.

**Comment by rmetzler** [comment]
@booyaa Could you please provide the config for nginx? We're trying to run gotty behind a custom proxy and experiencing the weird `var gotty_auth_token = '';`. My co-worker told me, he already uses `-c` but I'm going to double check.

**Comment by booyaa** [comment]
@rmetzler here you go (sorry for the delay): [https://github.com/yudai/gotty/pull/44#issuecomment-135326818](https://github.com/yudai/gotty/pull/44#issuecomment-135326818)
