### ISSUE TITLE
Running gotty top gives a blank screen in browser

### ISSUE THREAD

**Issue by iamads** [yudai/gotty#73]
Doing gotty top gives me a black screen with no text on browser
![gotty](https://cloud.githubusercontent.com/assets/3141307/10338715/2c5c6836-6d25-11e5-81fd-0cf7f3c0573c.png)

And logs state : Failed to parse init message unexpected end of JSON input
![gottylog](https://cloud.githubusercontent.com/assets/3141307/10338755/5f1695e4-6d25-11e5-9399-acb2bd63c295.png)

Go version is 1.5.1 on linux/amd64 and ubuntu 12.04

**Comment by yudai** [comment]
Could you provide me your version and/or commit id of gotty?

**Comment by iamads** [comment]
gotty version 0.0.10

**Comment by yudai** [comment]
Could you try the v0.0.11? It has some bug fixes and they might fix your problem.

**Comment by iamads** [comment]
Yeah the update fixed it. Thanks :)
