### ISSUE TITLE
command not terminated when connection is lost

### ISSUE THREAD

**Issue by databus23** [yudai/gotty#81]
I just played with gotty, looks pretty rad.

I noticed that when I run `gotty -w bash` and close the tab/browser the bash process spawned by potty stays around forever. I tried using `--close-signal` but that does not seem to do anything for me in this case.

In the log says:

```
2015/11/23 22:24:30 New client connected: [::1]:55807
2015/11/23 22:24:30 Command is running for client [::1]:55807 with PID 2423 (args="")
2015/11/23 22:24:30 [::1]:55807 101 GET /ws
2015/11/23 22:25:10 websocket: close 1006 unexpected EOF
```

Is this intended behaviour?

**Comment by databus23** [comment]
Small update: Seems its hanging at [context.pty.Close()](https://github.com/yudai/gotty/blob/master/app/client_context.go#L74)

**Comment by databus23** [comment]
This seems to be OSX/Darwin related. Can't reproduce on Linux.

**Comment by ekzhu** [comment]
Same issue on OSX here. I defer the close statement so the process cleanup can proceed, but the thread still hanging at context.pty.Close().

**Comment by yudai** [comment]
Should be fixed in the master branch. Let me know when it still exists.
