### ISSUE TITLE
Broken source release 0.0.12

### ISSUE THREAD

**Issue by uovobw** [yudai/gotty#83]
The current source release is unbuildable due to missing dependencies:
- there is no straightforward way to install or signal the absence of `go-bindata` (that can be resolved by a `go get -u github.com/jteeuwen/go-bindata/...` but it's not that immediate
- the directory `libapps` is empty and the make fails, cloning manually from `https://chromium.googlesource.com/apps/libapps` in libapps solves the problem

how can i help fixing this? i would suggest that for the first problem a simple makefile failure prompting the user to install `go-bindata` (since she is building from source she must already have a working go env) might suffice. 
For the second problem i am not sure you can simply ship the whole `libapps` dir, so maybe that can be fixed by either shipping the file or adding a `git clone https://chromium.googlesource.com/apps/libapps libapps/` step...

let me know what you think!

**Comment by uovobw** [comment]
@yudai any insight on this?

**Comment by sratatata** [comment]
not working for me...

**Comment by eush77** [comment]
> For the second problem i am not sure you can simply ship the whole `libapps` dir, so maybe that can be fixed by either shipping the file or adding a `git clone https://chromium.googlesource.com/apps/libapps libapps/` step...

`libapps` is listed in `.gitmodules`, so `git submodule update` should work, too.

Unfortunately, this advice doesn't work for me either, same error…

**Comment by yudai** [comment]
Hi, thanks for feedback.

I added `go get -u github.com/jteeuwen/go-bindata/...` to Make file.

As for `libapps`, as @eush77 mentioned, you need to checkout the submodule.
