### ISSUE TITLE
 runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by D4prog** [yudai/gotty#84]
I installed gotty just now.

`~$ gotty ls`

> 2016/01/09 15:35:28 Server is starting with command: ls
2016/01/09 15:35:28 URL: http://127.0.0.1:8080/
2016/01/09 15:35:28 URL: http://[::1]:8080/
2016/01/09 15:35:28 URL: http://192.168.12.2:8080/
2016/01/09 15:35:28 URL: http://[fe80::7864:93ff:fe85:51e8]:8080/
2016/01/09 15:35:28 URL: http://172.17.0.1:8080/
2016/01/09 15:35:28 URL: http://[fe80::42:d2ff:fef8:e9b3]:8080/

I accessed http://127.0.0.1:8080/ and  I got error.

> 2016/01/09 15:35:31  http: panic serving 127.0.0.1:45398: runtime error: invalid memory address or nil pointer dereference
goroutine 22 [running]:
net/http.(*conn).serve.func1(0xc8200ce580, 0x7fe6ab92b000, 0xc8200cc020)
	/usr/lib/go/src/net/http/server.go:1287 +0xb5
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc820013530, 0xc8200d2be0, 0x11, 0x0, 0x0, 0x0, 0x0)
	/home/quartz/.go/third-party/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x22e
net/http.serveFile(0x7fe6ab92b1b8, 0xc8200d2a20, 0xc8200e0380, 0x7fe6ad1729f0, 0xc820013530, 0x80c478, 0x1, 0xc800000001)
	/usr/lib/go/src/net/http/fs.go:394 +0x5b1
net/http.(*fileHandler).ServeHTTP(0xc8200a42b0, 0x7fe6ab92b1b8, 0xc8200d2a20, 0xc8200e0380)
	/usr/lib/go/src/net/http/fs.go:483 +0x19c
net/http.StripPrefix.func1(0x7fe6ab92b1b8, 0xc8200d2a20, 0xc8200e0380)
	/usr/lib/go/src/net/http/server.go:1455 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc8200135c0, 0x7fe6ab92b1b8, 0xc8200d2a20, 0xc8200e0380)
	/usr/lib/go/src/net/http/server.go:1422 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820013590, 0x7fe6ab92b1b8, 0xc8200d2a20, 0xc8200e0380)
	/usr/lib/go/src/net/http/server.go:1699 +0x17d
github.com/yudai/gotty/app.wrapHeaders.func1(0x7fe6ab92b1b8, 0xc8200d2a20, 0xc8200e0380)
	/home/quartz/.go/third-party/src/github.com/yudai/gotty/app/app.go:389 +0xf1
net/http.HandlerFunc.ServeHTTP(0xc82000b460, 0x7fe6ab92b1b8, 0xc8200d2a20, 0xc8200e0380)
	/usr/lib/go/src/net/http/server.go:1422 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820013680, 0x7fe6ab92b1b8, 0xc8200d2a20, 0xc8200e0380)
	/usr/lib/go/src/net/http/server.go:1699 +0x17d
github.com/yudai/gotty/app.wrapLogger.func1(0x7fe6ab92b180, 0xc8200ce630, 0xc8200e0380)
	/home/quartz/.go/third-party/src/github.com/yudai/gotty/app/app.go:381 +0xd0
net/http.HandlerFunc.ServeHTTP(0xc82000b4a0, 0x7fe6ab92b180, 0xc8200ce630, 0xc8200e0380)
	/usr/lib/go/src/net/http/server.go:1422 +0x3a
github.com/braintree/manners.(*gracefulHandler).ServeHTTP(0xc82000bf60, 0x7fe6ab92b180, 0xc8200ce630, 0xc8200e0380)
	/home/quartz/.go/third-party/src/github.com/braintree/manners/server.go:262 +0x7e
net/http.serverHandler.ServeHTTP(0xc82001c420, 0x7fe6ab92b180, 0xc8200ce630, 0xc8200e0380)
	/usr/lib/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8200ce580)
	/usr/lib/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:1910 +0x3f6

**Comment by xyproto** [comment]
I get the same error. 64-bit Arch Linux. go 1.5.2

Can be reproduced by running just `gotty top` or `gotty htop`.

**Comment by uovobw** [comment]
@D4prog @xyproto i think this might be related to #83 and to the way `libapps` are pulled: if you clone the repository "as is" the `libapps` directory is empty, and the error that you see is related to "assetfs" that is trying to pull a non-esisting resource from the `bindata`-ed assets, failing. Refer to my workaround from #83 to fix it if you want to build from source or download one of the releases that are working.

**Comment by yudai** [comment]
Hi, thank you for the reports and patient.
I just released v0.0.13 and you should be able to build a workable binary with `go get` with this release.
