### ISSUE TITLE
Running gotty in a subfolder

### ISSUE THREAD

**Issue by madspooky** [yudai/gotty#92]
I was wondering if anyone could shed some light on running gotty in a subfolder in nginx i.e.:

www.example.com/gotty

I tried modifying the address command to point it to that folder however I get an error that it doesn't exist. I have a site already bound on 80 and 443 and would prefer to not use a non-standard port.

Thanks!

**Comment by yudai** [comment]
Hi @madspooky. I'm sorry for the delay to reply.
Do you still have the issue yet?

**Comment by madspooky** [comment]
Yes unfortunately I haven't been able to figure it out. Any suggestions would be appreciated. I'm wondering if it's because I'm running nginx and I would be better off with Apache

-----Original Message-----

**Comment by yudai** [comment]
Thanks for the response.
Is that possible to paste your config file of nginx?

**Comment by FryDay** [comment]
I can confirm this is an issue and am working on a fix. The problem is that gotty cannot find the javascript files if you use anything other than root. For example, www.example.com:8080 will work fine, but there is no support for www.example.com:8080/test. I will submit a pull request to address this soon.

**Comment by yudai** [comment]
As discussed in #113, the following example allows redirecting with a path.

```
  location /watchtop/ {
     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     proxy_set_header Host $http_host;
     proxy_set_header Upgrade $http_upgrade;
     proxy_set_header Connection "upgrade";
     proxy_redirect off;
     proxy_pass http://localhost:8080/;
  }
```
