### ISSUE TITLE
Please don't tar.gz the releases

### ISSUE THREAD

**Issue by ahmetalpbalkan** [yudai/gotty#94]
The release is already a single binary and it's not worth tar-ing them. It just makes the next person's (who is scripting installation of gotty) harder.

**Comment by yudai** [comment]
Hi @ahmetalpbalkan. Thank you for your feed back.
Unfortunately, I personally like this tar.gz style and have no plan to change this way now.
The one of the reasons is that I don't want to add suffix strings to binary files.
