### ISSUE TITLE
Start on a random port

### ISSUE THREAD

**Issue by ahmetb** [yudai/gotty#97]
Many server apps accept port number 0 and the system picks a random high port number available. `net.Listen` does that too. However when I start `gotty -p 0`, it actually prints out addresses like `http://[::]1:0/`, meaning it doesn't read the actual port number from the returned `net.Listener` and just looks at input.

**Comment by xiaods** [comment]
gotty have a ramdon url, do you have use it alternative?

**Comment by ahmetalpbalkan** [comment]
@xiaods not sure what you mean.

**Comment by yudai** [comment]
Currently I don't see use case for this issue. Let the issue open for further discussion.

**Comment by yudai** [comment]
I realized I misunderstood the point. I'll do something on this by v2.0.0.

**Comment by yudai** [comment]
Since go1.9 comes with `ServeTLS()` of `http.Server`, which is useful to start the server with a listner, I wait it to be released.

**Comment by yudai** [comment]
Fixed in the master branch. Now log shows the actual listening port.
Thanks!
