### ISSUE TITLE
Even with --title-format, title shows "GoTTY" briefly

### ISSUE THREAD

**Issue by ahmetb** [yudai/gotty#99]
The first request `GET /` returns this:

```
<!doctype html>
<html>
  <head>
    <title>GoTTY</title>
    <style>body {position: absolute; height: 100%; width: 100%; margin: 0px;}</style>
  </head>
  <body>
    <script src="hterm.js"></script>
    <script src="gotty.js"></script>
  </body>
</html>
```

This briefly shows GoTTY in my browser title even though I use `--title-format`. I bet we can make this use `--title-format` as well?

**Comment by yudai** [comment]
Hi @ahmetalpbalkan, thanks to the feed back.

Yes, currently the first HTML file sent by the server is a static one stored as a "bin-data". I think I can convert it a template file and fill with the value of `--tiltle-format`.

**Comment by yudai** [comment]
Fixed in the master branch. The index file is delivered with the title.
